services:
  say-db:
    image: mysql:8.0
    container_name: say-home-db
    restart: always
    environment:
      - MYSQL_DATABASE=say_home_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
  say-qdrant:
    image: qdrant/qdrant:latest
    container_name: say-home-vector-db
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - db_data:/qdrant/storage
    
volumes:
  db_data:
