services:
  say-db:
    image: mysql:8.0
    container_name: say-home-db
    restart: always
    environment:
      - MYSQL_DATABASE=say_home_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data:
