"use client;";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/shared/lib/utils";
import { AuthProvider } from "@/features/auth/context/AuthContext";
import { Toaster } from "@/shared/components/ui/sonner";
import { use } from "react";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Say Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className={`${inter.className} min-h-full flex flex-col`}>
        <AuthProvider>
          {children}{" "}
          <Toaster
            toastOptions={{
              classNames: {
                error: "!bg-red-500 !text-white !border-red-500",
              },
            }}
          />{" "}
        </AuthProvider>
      </body>
    </html>
  );
}
