package ma.sayhome.say_home_api.shared.enums;

public enum ProspectPropertyDocumentType {
    BEFORE_SALE_DOCUMENT,
    BEFORE_RENTAL_DOCUMENT,
    SALE_DEED,
    LEASE_CONTRACT,
    LAND_TITLE,
    MORTGAGE_CONTRACT,
    PAYMENT_RECEIPT,
    RENT_RECEIPT,
    PROPERTY_INSPECTION_REPORT,
    SECURITY_DEPOSIT_RECEIPT,
    RECEIPT,
    CONTRACT,
    PAYMENT_PROOF,
    ID_COPY,
    OTHER
}
