sonar.projectKey=yagashirag77_say-home-q-test
sonar.organization=yagashirag77
sonar.host.url=https://sonarcloud.io
# sonar.token=0de7c509a4f65bfca3f46a83b0a781f209579fe7
sonar.sources=src/main
sonar.tests=src/test
sonar.sourceEncoding=UTF-8
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
