export const APP_ROUTES = {
  HOME: "/dashboard",
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  FORGOT_PASSWORD: "/auth/forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  PROFILE: "/user/profile",

  PROSPECTS: "/prospects",
  PROSPECTS_NEW: "/prospects/new",
  PROPERTIES: "/properties",
  PIPELINE: "/pipeline",
  AI_MATCHING: "/ai-matching",
  APPOINTMENTS: "/appointments",
  APPOINTMENTS_NEW: "/appointments/new",
  TICKETS: "/tickets",
  CHATS: "/chats",
  AGENTS: "/agents",
  USERS_NEW: "/agents/new",
} as const;
