spring.application.name=say-home-api
server.port=8080
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/say_home_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
ai.server.url=http://localhost:8000
cloudinary.api.key=913849991379113
cloudinary.api.secret=mgQySZIqK7DYAhcUL5wdCXW2MF4
cloudinary.cloud-name=dfxijqjo5
#spring.jackson.serialization.fail-on-empty-beans=false

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:sayhome.app@gmail.com}
spring.mail.password=${MAIL_PASSWORD:zxwxfnqnbxjvksmc}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS:true}
